# Dokploy Configuration for Biskaken Auto Admin Dashboard
# Deploy at: bisadmin.rpnmore.com

version: '3.8'

services:
  # PostgreSQL Database
  biskaken-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-biskaken_auto}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - biskaken-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-biskaken_auto}"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "dokploy.project=biskaken-admin"
      - "dokploy.service=database"

  # FastAPI Backend
  biskaken-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD}@biskaken-postgres:5432/${DB_NAME:-biskaken_auto}
      DB_HOST: biskaken-postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-biskaken_auto}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      ENVIRONMENT: production
      PORT: 8000
      CORS_ORIGINS: https://bisadmin.rpnmore.com,https://biskakenauto.rpnmore.com
    depends_on:
      biskaken-postgres:
        condition: service_healthy
    networks:
      - biskaken-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "dokploy.project=biskaken-admin"
      - "dokploy.service=api"
      - "traefik.enable=true"
      - "traefik.http.routers.biskaken-api.rule=Host(`bisadmin.rpnmore.com`) && PathPrefix(`/api`, `/health`)"
      - "traefik.http.routers.biskaken-api.tls=true"
      - "traefik.http.routers.biskaken-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.biskaken-api.loadbalancer.server.port=8000"

  # React Frontend (Admin Dashboard)
  biskaken-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_URL: https://bisadmin.rpnmore.com
      VITE_APP_TITLE: Biskaken Auto Admin
      VITE_ENVIRONMENT: production
      NODE_ENV: production
    depends_on:
      - biskaken-api
    networks:
      - biskaken-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "dokploy.project=biskaken-admin"
      - "dokploy.service=frontend"
      - "traefik.enable=true"
      - "traefik.http.routers.biskaken-frontend.rule=Host(`bisadmin.rpnmore.com`)"
      - "traefik.http.routers.biskaken-frontend.tls=true"
      - "traefik.http.routers.biskaken-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.biskaken-frontend.loadbalancer.server.port=3000"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.biskaken-frontend-redirect.rule=Host(`bisadmin.rpnmore.com`)"
      - "traefik.http.routers.biskaken-frontend-redirect.entrypoints=web"
      - "traefik.http.routers.biskaken-frontend-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

volumes:
  postgres_data:
    driver: local
    labels:
      - "dokploy.project=biskaken-admin"
      - "dokploy.volume=postgres-data"

networks:
  biskaken-network:
    driver: bridge
    labels:
      - "dokploy.project=biskaken-admin"
      - "dokploy.network=main"