import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { ApiResponse } from '../types';
/**
 * Generic validation middleware factory
 */
export declare const validate: (schema: z.ZodSchema) => (req: Request, res: Response<ApiResponse>, next: NextFunction) => Response<ApiResponse<any>, Record<string, any>>;
export declare const schemas: {
    login: z.ZodObject<{
        body: z.ZodObject<{
            email: z.ZodString;
            password: z.ZodString;
        }, z.core.$strip>;
    }, z.core.$strip>;
    register: z.ZodObject<{
        body: z.ZodObject<{
            name: z.ZodString;
            email: z.ZodString;
            phone: z.ZodOptional<z.ZodString>;
            password: z.ZodString;
            role: z.ZodOptional<z.ZodEnum<{
                ADMIN: "ADMIN";
                SUB_ADMIN: "SUB_ADMIN";
                STAFF: "STAFF";
            }>>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    changePassword: z.ZodObject<{
        body: z.ZodObject<{
            currentPassword: z.ZodString;
            newPassword: z.ZodString;
        }, z.core.$strip>;
    }, z.core.$strip>;
    createCustomer: z.ZodObject<{
        body: z.ZodObject<{
            name: z.ZodString;
            phone: z.ZodString;
            email: z.ZodOptional<z.ZodString>;
            address: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
            vehicle: z.ZodObject<{
                make: z.ZodString;
                model: z.ZodString;
                year: z.ZodNumber;
                plateNumber: z.ZodOptional<z.ZodString>;
                vin: z.ZodOptional<z.ZodString>;
                notes: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateCustomer: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
        body: z.ZodObject<{
            name: z.ZodOptional<z.ZodString>;
            phone: z.ZodOptional<z.ZodString>;
            email: z.ZodOptional<z.ZodString>;
            address: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    createJob: z.ZodObject<{
        body: z.ZodObject<{
            customerId: z.ZodString;
            vehicleId: z.ZodString;
            complaint: z.ZodString;
            priority: z.ZodOptional<z.ZodEnum<{
                LOW: "LOW";
                MEDIUM: "MEDIUM";
                HIGH: "HIGH";
            }>>;
            laborHours: z.ZodOptional<z.ZodNumber>;
            laborRate: z.ZodOptional<z.ZodNumber>;
            estimatedCost: z.ZodOptional<z.ZodNumber>;
            expectedCompletion: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateJob: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
        body: z.ZodObject<{
            complaint: z.ZodOptional<z.ZodString>;
            diagnosis: z.ZodOptional<z.ZodString>;
            status: z.ZodOptional<z.ZodEnum<{
                PENDING: "PENDING";
                IN_PROGRESS: "IN_PROGRESS";
                COMPLETED: "COMPLETED";
                CANCELLED: "CANCELLED";
            }>>;
            priority: z.ZodOptional<z.ZodEnum<{
                LOW: "LOW";
                MEDIUM: "MEDIUM";
                HIGH: "HIGH";
            }>>;
            assignedTo: z.ZodOptional<z.ZodString>;
            laborHours: z.ZodOptional<z.ZodNumber>;
            laborRate: z.ZodOptional<z.ZodNumber>;
            estimatedCost: z.ZodOptional<z.ZodNumber>;
            actualCost: z.ZodOptional<z.ZodNumber>;
            expectedCompletion: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateJobStatus: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
        body: z.ZodObject<{
            status: z.ZodEnum<{
                PENDING: "PENDING";
                IN_PROGRESS: "IN_PROGRESS";
                COMPLETED: "COMPLETED";
                CANCELLED: "CANCELLED";
            }>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    createInventoryItem: z.ZodObject<{
        body: z.ZodObject<{
            partName: z.ZodString;
            category: z.ZodString;
            stockQty: z.ZodNumber;
            reorderLevel: z.ZodNumber;
            unitCost: z.ZodNumber;
            sellingPrice: z.ZodNumber;
            supplier: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateInventoryItem: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
        body: z.ZodObject<{
            partName: z.ZodOptional<z.ZodString>;
            category: z.ZodOptional<z.ZodString>;
            stockQty: z.ZodOptional<z.ZodNumber>;
            reorderLevel: z.ZodOptional<z.ZodNumber>;
            unitCost: z.ZodOptional<z.ZodNumber>;
            sellingPrice: z.ZodOptional<z.ZodNumber>;
            supplier: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    createInvoice: z.ZodObject<{
        body: z.ZodObject<{
            customerId: z.ZodString;
            jobId: z.ZodOptional<z.ZodString>;
            dueDate: z.ZodOptional<z.ZodString>;
            tax: z.ZodOptional<z.ZodNumber>;
            discount: z.ZodOptional<z.ZodNumber>;
            notes: z.ZodOptional<z.ZodString>;
            items: z.ZodArray<z.ZodObject<{
                partId: z.ZodOptional<z.ZodString>;
                description: z.ZodString;
                quantity: z.ZodNumber;
                unitPrice: z.ZodNumber;
            }, z.core.$strip>>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    recordPayment: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
        body: z.ZodObject<{
            amount: z.ZodNumber;
            method: z.ZodEnum<{
                CASH: "CASH";
                MOBILE_MONEY: "MOBILE_MONEY";
                CARD: "CARD";
                BANK_TRANSFER: "BANK_TRANSFER";
                USDT: "USDT";
            }>;
            reference: z.ZodOptional<z.ZodString>;
            notes: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    pagination: z.ZodObject<{
        query: z.ZodObject<{
            page: z.ZodOptional<z.ZodPipe<z.ZodString, z.ZodTransform<number, string>>>;
            limit: z.ZodOptional<z.ZodPipe<z.ZodString, z.ZodTransform<number, string>>>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    uuidParam: z.ZodObject<{
        params: z.ZodObject<{
            id: z.ZodString;
        }, z.core.$strip>;
    }, z.core.$strip>;
};
//# sourceMappingURL=validation.d.ts.map